import { useState } from 'react';
import { Check, ChevronRight, CircleAlert, Clock3, ExternalLink, GitBranch, MessageSquare, MoreHorizontal, UserRound } from 'lucide-react';

const timeline = [
  { time: '14:32', title: 'Incident opened automatically', text: 'Run #106 failed its integration stage on feature/cart.', icon: CircleAlert, tone: 'text-rose-600 bg-rose-50 dark:bg-rose-950/30 dark:text-rose-300' },
  { time: '14:33', title: 'Diagnosis attached', text: 'NEXUS identified a missing AUTH_TOKEN in the Docker test container.', icon: MessageSquare, tone: 'text-violet-600 bg-violet-50 dark:bg-violet-950/30 dark:text-violet-300' },
  { time: '14:37', title: 'Patch proposed', text: 'Recommendation R-019 is ready for review by the assigned owner.', icon: GitBranch, tone: 'text-indigo-600 bg-indigo-50 dark:bg-indigo-950/30 dark:text-indigo-300' },
];

const secondary = [
  ['INC-018', 'Checkout contract test flake', 'Investigating', 'feature/cart', '1h 24m'],
  ['INC-017', 'Image scan timeout', 'Monitoring', 'main', 'Yesterday'],
  ['INC-016', 'Preview deploy permission denied', 'Resolved', 'feature/auth', 'Yesterday'],
];

function Status({ children, tone }) { return <span className={`inline-flex items-center gap-1.5 px-2 py-1 text-[10px] font-bold ${tone}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{children}</span>; }

export default function Incidents() {
  const [resolved, setResolved] = useState(false);
  return <div className="space-y-5">
    <section className="flex flex-col gap-3 border-b border-slate-200 pb-5 dark:border-slate-800 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Incident management</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-slate-950 dark:text-white">Keep delivery failures owned.</h1><p className="mt-1 text-sm text-slate-500">Pipeline failures become incidents when they need a decision, not just a retry.</p></div><div className="flex items-center gap-2"><span className="text-xs text-slate-500">Open</span><span className="bg-rose-100 px-2 py-1 text-xs font-bold text-rose-700 dark:bg-rose-950 dark:text-rose-300">02</span></div></section>
    <section className={`border p-5 ${resolved ? 'border-emerald-200 bg-emerald-50/40 dark:border-emerald-900 dark:bg-emerald-950/15' : 'border-rose-200 bg-white dark:border-rose-900/70 dark:bg-[#0e141d]'}`}><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center ${resolved ? 'bg-emerald-600 text-white' : 'bg-rose-600 text-white'}`}>{resolved ? <Check size={18}/> : <CircleAlert size={18}/>}</div><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-xs font-bold text-slate-500">INC-019</p>{resolved ? <Status tone="bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">RESOLVED</Status> : <Status tone="bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300">OPEN</Status>}</div><h2 className="mt-2 text-lg font-bold tracking-tight text-slate-950 dark:text-white">Integration tests are missing an authentication token.</h2><p className="mt-1 text-sm leading-6 text-slate-500">Run #106 failed after the Docker test container started without <code className="bg-slate-100 px-1 font-mono text-xs text-slate-700 dark:bg-slate-800 dark:text-slate-200">AUTH_TOKEN</code>.</p></div></div><div className="flex shrink-0 flex-wrap items-center gap-2"><button className="button-secondary"><ExternalLink size={13}/>View run</button><button onClick={() => setResolved(!resolved)} className={resolved ? 'button-secondary' : 'button-primary'}>{resolved ? 'Reopen incident' : <><Check size={14}/>Mark resolved</>}</button></div></div><div className="mt-5 grid border-t border-slate-100 pt-4 dark:border-slate-800 md:grid-cols-3"><div className="border-b border-slate-100 pb-4 dark:border-slate-800 md:border-b-0 md:border-r md:pr-5"><p className="eyebrow">Owner</p><div className="mt-2 flex items-center gap-2"><div className="grid h-6 w-6 place-items-center rounded-full bg-slate-200 text-[9px] font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-200">SK</div><span className="text-xs font-semibold text-slate-700 dark:text-slate-200">Shubham Kumar</span></div></div><div className="border-b border-slate-100 py-4 dark:border-slate-800 md:border-b-0 md:border-r md:px-5 md:py-0"><p className="eyebrow">Affected surface</p><p className="mt-2 flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-200"><GitBranch size={13} className="text-slate-400"/>api-service · feature/cart</p></div><div className="pt-4 md:pl-5 md:pt-0"><p className="eyebrow">Time open</p><p className="mt-2 flex items-center gap-1.5 text-xs font-semibold text-slate-700 dark:text-slate-200"><Clock3 size={13} className="text-slate-400"/> {resolved ? 'Resolved after 11m' : '11 minutes'}</p></div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="panel dark:border-slate-800 dark:bg-[#0e141d]"><div className="panel-heading dark:border-slate-800"><p className="text-sm font-bold text-slate-900 dark:text-white">Activity timeline</p><p className="mt-0.5 text-xs text-slate-500">System events and owner actions</p></div><div className="p-5">{timeline.map(({ time, title, text, icon: Icon, tone }, index) => <div key={title} className="relative flex gap-3 pb-6 last:pb-0">{index < timeline.length - 1 && <span className="absolute left-3 top-7 h-[calc(100%-16px)] w-px bg-slate-200 dark:bg-slate-700"/>}<div className={`z-10 grid h-6 w-6 shrink-0 place-items-center ${tone}`}><Icon size={13}/></div><div className="min-w-0"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold text-slate-800 dark:text-slate-100">{title}</p><time className="font-mono text-[10px] text-slate-400">{time}</time></div><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>)}</div></div><div className="panel dark:border-slate-800 dark:bg-[#0e141d]"><div className="panel-heading flex items-center justify-between dark:border-slate-800"><div><p className="text-sm font-bold text-slate-900 dark:text-white">Other incidents</p><p className="mt-0.5 text-xs text-slate-500">Recent incident queue</p></div><button className="icon-button" aria-label="More incident options"><MoreHorizontal size={15}/></button></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{secondary.map(([id, title, state, branch, age]) => <button key={id} className="grid w-full grid-cols-[1fr_auto] gap-3 px-5 py-3 text-left hover:bg-slate-50 dark:hover:bg-slate-900"><div><p className="font-mono text-[10px] font-bold text-slate-400">{id}</p><p className="mt-1 text-xs font-semibold text-slate-700 dark:text-slate-200">{title}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-slate-400"><UserRound size={11}/>{branch}</p></div><div className="flex flex-col items-end justify-between"><span className={`text-[10px] font-bold ${state === 'Resolved' ? 'text-emerald-600' : state === 'Monitoring' ? 'text-amber-600' : 'text-rose-600'}`}>{state.toUpperCase()}</span><span className="text-[10px] text-slate-400">{age}</span></div></button>)}</div></div></section>
  </div>;
}
