import { Check, CircleDot, Clock3, Copy, GitBranch, RotateCw, Terminal, X } from 'lucide-react';

const stages = [
  { name: 'Build', duration: '1m 10s', state: 'complete' },
  { name: 'Tests', duration: '2m 05s', state: 'complete' },
  { name: 'Integration', duration: '0m 57s', state: 'failed' },
  { name: 'Security', duration: 'Not started', state: 'waiting' },
  { name: 'Deploy', duration: 'Not started', state: 'waiting' },
];

function Stage({ stage, last }) {
  const styles = { complete: 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-300', failed: 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-300', waiting: 'border-slate-200 bg-white text-slate-400 dark:border-slate-700 dark:bg-[#0e141d] dark:text-slate-500' };
  const mark = stage.state === 'complete' ? <Check size={14}/> : stage.state === 'failed' ? <X size={14}/> : <CircleDot size={13}/>;
  return <div className="relative min-w-[138px] flex-1"><div className={`relative z-10 border px-3 py-3 ${styles[stage.state]}`}><div className="flex items-center justify-between"><span className="text-xs font-bold">{stage.name}</span>{mark}</div><p className="mt-1 text-[10px] opacity-75">{stage.duration}</p></div>{!last && <div className="absolute left-full top-1/2 z-0 hidden h-px w-4 -translate-y-1/2 bg-slate-300 dark:bg-slate-700 xl:block"/>}</div>;
}

export default function PipelineDetails() {
  return <div className="space-y-5">
    <section className="flex flex-col gap-4 border-b border-slate-200 pb-5 dark:border-slate-800 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3"><p className="font-mono text-2xl font-bold tracking-tight text-slate-950 dark:text-white">#106</p><span className="inline-flex items-center gap-1.5 bg-rose-50 px-2 py-1 text-[11px] font-bold text-rose-700 dark:bg-rose-950/40 dark:text-rose-300"><span className="h-1.5 w-1.5 bg-rose-500"/>FAILED</span></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500"><span className="flex items-center gap-1.5"><GitBranch size={14}/>feature/cart</span><code className="border border-slate-200 bg-white px-1.5 py-0.5 text-[11px] text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">91bc21d</code><span className="flex items-center gap-1.5"><Clock3 size={14}/>Started 5 hours ago · 4m 12s</span></div></div><button className="button-secondary"><RotateCw size={14}/>Re-run workflow</button></section>
    <section className="panel dark:border-slate-800 dark:bg-[#0e141d]"><div className="panel-heading dark:border-slate-800"><p className="text-sm font-bold text-slate-900 dark:text-white">Execution path</p><p className="mt-0.5 text-xs text-slate-500">The workflow stopped after the integration stage failed.</p></div><div className="flex gap-4 overflow-x-auto p-5">{stages.map((stage, index) => <Stage key={stage.name} stage={stage} last={index === stages.length - 1}/>)}</div></section>
    <section className="overflow-hidden border border-slate-800 bg-[#0a0f16]"><div className="flex items-center justify-between border-b border-slate-800 bg-[#101720] px-4 py-3"><div className="flex items-center gap-2"><Terminal size={15} className="text-slate-400"/><span className="font-mono text-xs font-semibold text-slate-200">integration-tests</span><span className="border border-rose-900/70 bg-rose-950/40 px-1.5 py-0.5 text-[10px] font-bold text-rose-300">EXIT 1</span></div><button className="text-slate-500 transition hover:text-slate-200" aria-label="Copy output"><Copy size={14}/></button></div><pre className="max-h-[410px] overflow-auto p-5 font-mono text-[12px] leading-6 text-slate-300"><span className="text-slate-500">14:32:01  </span>Preparing test environment...{`\n`}<span className="text-slate-500">14:32:05  </span>postgres://test-db:5432/nexus_test  <span className="text-emerald-400">connected</span>{`\n`}<span className="text-slate-500">14:32:12  </span>pytest tests/integration/test_cart_checkout.py{`\n\n`}<span className="text-rose-400">FAILED  tests/integration/test_cart_checkout.py::test_checkout_session</span>{`\n`}<span className="text-rose-300">E   AuthenticationError: request returned HTTP 500</span>{`\n`}<span className="text-slate-500">E   app/services/auth.py:48 in create_session</span>{`\n`}<span className="text-slate-300">E       assert response.status_code == 200</span>{`\n`}<span className="text-rose-300">E       AssertionError: 500 != 200</span>{`\n\n`}<span className="text-amber-300">NOTICE  </span><span className="text-slate-400">AUTH_TOKEN was not available to the Docker test container.</span>{`\n`}<span className="text-slate-500">========================= 1 failed, 18 passed in 57.42s =========================</span></pre></section>
  </div>;
}
